# Generated by Django 6.0.5 on 2026-05-20 13:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_category_remove_book_author_manufacturer_product_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Author",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("birth_year", models.IntegerField()),
                ("rating", models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("pages", models.IntegerField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=8)),
                ("published_year", models.IntegerField()),
                ("stock", models.IntegerField()),
            ],
        ),
        migrations.RemoveConstraint(
            model_name="manufacturer",
            name="unique_manufacturer_name",
        ),
        migrations.RemoveConstraint(
            model_name="manufacturer",
            name="check_manufacturer_name_not_empty",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_price_d352a5_idx",
        ),
        migrations.RemoveIndex(
            model_name="product",
            name="app_product_status_5246b8_idx",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="unique_product_name",
        ),
        migrations.RemoveConstraint(
            model_name="product",
            name="check_product_price",
        ),
        migrations.AddField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="app.author",
            ),
        ),
        migrations.RemoveField(
            model_name="product",
            name="additional_categories",
        ),
        migrations.RemoveField(
            model_name="product",
            name="category",
        ),
        migrations.RemoveField(
            model_name="product",
            name="manufacturer",
        ),
        migrations.DeleteModel(
            name="Category",
        ),
        migrations.DeleteModel(
            name="Manufacturer",
        ),
        migrations.DeleteModel(
            name="Product",
        ),
    ]
