# Generated by Django 6.0.4 on 2026-05-25 15:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0005_author_book_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Publishment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(max_length=255, verbose_name="Назва видавництва"),
                ),
            ],
            options={
                "verbose_name": "Видавництво",
                "verbose_name_plural": "Видавництва",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="author",
            options={
                "ordering": ["name"],
                "verbose_name": "Автор",
                "verbose_name_plural": "Автори",
            },
        ),
        migrations.AlterModelOptions(
            name="book",
            options={
                "ordering": ["-published_year", "title"],
                "verbose_name": "Книга",
                "verbose_name_plural": "Книги",
            },
        ),
        migrations.AlterField(
            model_name="author",
            name="birth_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Рік народження"
            ),
        ),
        migrations.AlterField(
            model_name="author",
            name="name",
            field=models.CharField(max_length=255, verbose_name="Ім'я"),
        ),
        migrations.AlterField(
            model_name="author",
            name="rating",
            field=models.FloatField(default=0.0, verbose_name="Рейтинг"),
        ),
        migrations.AlterField(
            model_name="book",
            name="author",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="app.author",
                verbose_name="Автор",
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Кількість сторінок"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="price",
            field=models.DecimalField(
                decimal_places=2, max_digits=8, verbose_name="Ціна"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="published_year",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Рік видання"
            ),
        ),
        migrations.AlterField(
            model_name="book",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="Залишок на складі"),
        ),
        migrations.AlterField(
            model_name="book",
            name="title",
            field=models.CharField(max_length=255, verbose_name="Назва"),
        ),
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Назва країни")),
            ],
            options={
                "verbose_name": "Країна",
                "verbose_name_plural": "Країни",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="app_country_name_49b65d_idx")
                ],
            },
        ),
        migrations.AddField(
            model_name="author",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="authors",
                to="app.country",
                verbose_name="Країна",
            ),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["name"], name="app_author_name_2882be_idx"),
        ),
        migrations.AddIndex(
            model_name="author",
            index=models.Index(fields=["rating"], name="app_author_rating_08c011_idx"),
        ),
        migrations.AddField(
            model_name="publishment",
            name="country",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="publishments",
                to="app.country",
                verbose_name="Країна",
            ),
        ),
        migrations.AddField(
            model_name="book",
            name="publishment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="books",
                to="app.publishment",
                verbose_name="Видавництво",
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["title"], name="app_book_title_b42076_idx"),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(
                fields=["published_year"], name="app_book_publish_484631_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="book",
            index=models.Index(fields=["price"], name="app_book_price_937c2e_idx"),
        ),
        migrations.AddIndex(
            model_name="publishment",
            index=models.Index(fields=["name"], name="app_publish_name_c880eb_idx"),
        ),
    ]
