# Generated by Django 6.0.4 on 2026-05-27 12:22

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0006_publishment_alter_author_options_alter_book_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=100, unique=True, verbose_name="Назва категорії"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL-friendly назва", max_length=120, unique=True
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Опис")),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
            ],
            options={
                "verbose_name": "Категорія",
                "verbose_name_plural": "Категорії",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Manufacturer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=150, unique=True, verbose_name="Назва виробника"
                    ),
                ),
                ("country", models.CharField(max_length=100, verbose_name="Країна")),
                (
                    "website",
                    models.URLField(blank=True, null=True, verbose_name="Веб-сайт"),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="manufacturers/logos/",
                        verbose_name="Логотип",
                    ),
                ),
                (
                    "established_year",
                    models.PositiveIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1800),
                            django.core.validators.MaxValueValidator(2026),
                        ],
                        verbose_name="Рік заснування",
                    ),
                ),
            ],
            options={
                "verbose_name": "Виробник",
                "verbose_name_plural": "Виробники",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Назва товару")),
                (
                    "slug",
                    models.SlugField(max_length=250, unique=True, verbose_name="Slug"),
                ),
                ("description", models.TextField(verbose_name="Опис")),
                (
                    "short_description",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Короткий опис"
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(0)],
                        verbose_name="Ціна",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="Ціна зі знижкою",
                    ),
                ),
                (
                    "stock_quantity",
                    models.PositiveIntegerField(
                        default=0, verbose_name="Кількість на складі"
                    ),
                ),
                (
                    "sku",
                    models.CharField(
                        max_length=50, unique=True, verbose_name="Артикул (SKU)"
                    ),
                ),
                (
                    "weight",
                    models.FloatField(blank=True, null=True, verbose_name="Вага (кг)"),
                ),
                (
                    "is_available",
                    models.BooleanField(
                        default=True, verbose_name="Доступний для продажу"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Чернетка"),
                            ("published", "Опубліковано"),
                            ("archived", "Архівовано"),
                        ],
                        default="draft",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(blank=True, default=list, verbose_name="Теги"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата створення"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата оновлення"),
                ),
                (
                    "published_at",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата публікації"
                    ),
                ),
            ],
            options={
                "verbose_name": "Товар",
                "verbose_name_plural": "Товари",
                "ordering": ["-created_at"],
            },
        ),
        migrations.RemoveIndex(
            model_name="author",
            name="app_author_name_2882be_idx",
        ),
        migrations.RemoveIndex(
            model_name="author",
            name="app_author_rating_08c011_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="app_book_title_b42076_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="app_book_publish_484631_idx",
        ),
        migrations.RemoveIndex(
            model_name="book",
            name="app_book_price_937c2e_idx",
        ),
        migrations.RemoveIndex(
            model_name="country",
            name="app_country_name_49b65d_idx",
        ),
        migrations.RemoveIndex(
            model_name="publishment",
            name="app_publish_name_c880eb_idx",
        ),
        migrations.AddField(
            model_name="product",
            name="additional_categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="additional_products",
                to="app.category",
                verbose_name="Додаткові категорії",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="app.category",
                verbose_name="Категорія",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="manufacturer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="products",
                to="app.manufacturer",
                verbose_name="Виробник",
            ),
        ),
        migrations.RemoveField(
            model_name="author",
            name="country",
        ),
        migrations.RemoveField(
            model_name="book",
            name="author",
        ),
        migrations.RemoveField(
            model_name="book",
            name="publishment",
        ),
        migrations.RemoveField(
            model_name="publishment",
            name="country",
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["price"], name="app_product_price_d352a5_idx"),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["status"], name="app_product_status_5246b8_idx"),
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Book",
        ),
        migrations.DeleteModel(
            name="Country",
        ),
        migrations.DeleteModel(
            name="Publishment",
        ),
    ]
