# Generated by Django 6.0.4 on 2026-05-27 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0007_category_manufacturer_product_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="category",
            name="slug",
        ),
        migrations.RemoveField(
            model_name="product",
            name="sku",
        ),
        migrations.RemoveField(
            model_name="product",
            name="slug",
        ),
    ]
